### ISSUE TITLE
Task1: Processing raw data

### ISSUE THREAD

**Issue by parth1007** [opencodeiiita/EmotionAnalysis#1]
You'll find 2 types of data in the Dataset folder, raw and filtered. For this task let's have a look at the raw data.

Your task is to filter this data as you find suitable, get everything useful out of those CSV files, and create a new pandas data frame.
**Note**: You need to just filter the data, no processing other than deletion and merging is required.

**Comment by KBVijayVarma** [comment]
Claim

**Comment by indrasn0wal** [comment]
claim

**Comment by sunny7712** [comment]
claim

**Comment by Phantom-Harsh** [comment]
Claim

**Comment by ykings12** [comment]
Claim

**Comment by Parvish-Kakarapalli** [comment]
claim

**Comment by RiyaParikh0112** [comment]
Claim
