### ISSUE TITLE
Task4: Quantitative Analysis

### ISSUE THREAD

**Issue by parth1007** [opencodeiiita/EmotionAnalysis#13]
Now we get into the data visualization part. You need to check the distribution of the number of labels for each piece of text. Plot a bar chart for the same.

A file with the list of emotions has been added to the repo to make things easier.

**Comment by indrasn0wal** [comment]
claim

**Comment by Parvish-Kakarapalli** [comment]
Claim

**Comment by KBVijayVarma** [comment]
Claim

**Comment by KBVijayVarma** [comment]
Should I plot a Bar Chart for the train.tsv file or filtered_dataset.csv made from raw_dataset(Issue 1) @parth1007 ?

**Comment by parth1007** [comment]
train.tsv

**Comment by KBVijayVarma** [comment]
@Parvish-Kakarapalli already done this and submitted the PR, so it is better to assign the task to him.

**Comment by parth1007** [comment]
No problem, you both can submit.

**Comment by KBVijayVarma** [comment]
Ok

**Comment by sunny7712** [comment]
Claim
