### ISSUE TITLE
Task2: Creating dataframe

### ISSUE THREAD

**Issue by parth1007** [opencodeiiita/EmotionAnalysis#2]
Convert train.tsv file into a dataframe with suitable column names and add column named emotion (which contains the word for respective emotion rather than an integer).

**Note**: Hardcoding of any type is not allowed.

**Comment by KBVijayVarma** [comment]
Claim

**Comment by indrasn0wal** [comment]
claim

**Comment by KBVijayVarma** [comment]
Hi @parth1007 is it not First Come First Serve Basis for assigning the Issues?

**Comment by sunny7712** [comment]
Claim

**Comment by ykings12** [comment]
Claim

**Comment by parth1007** [comment]
Yes @KBVijayVarma , but there is a limit of 1 issue assigned per repo at a time. You already had task 1 assigned.

**Comment by Parvish-Kakarapalli** [comment]
Claim

**Comment by KBVijayVarma** [comment]
Ok @parth1007. Thanks
