### ISSUE TITLE
Text cleaning

### ISSUE THREAD

**Issue by parth1007** [opencodeiiita/EmotionAnalysis#24]
Enough with EDA, We will now head on to data preprocessing. You need to clean the text and make it ready to tokenize. You can use whatever cleaning methods you want. Points will be awarded on basis of the quality of the submission. Note: the output result should still be text, don't convert it to numeric yet.

**Comment by Parvish-Kakarapalli** [comment]
claim

**Comment by parth1007** [comment]
Deadline for this task: 26 dec
