### ISSUE TITLE
Task3: Mapping classes

### ISSUE THREAD

**Issue by parth1007** [opencodeiiita/EmotionAnalysis#8]
Consider train.tsv, Convert it into a pandas dataframe, and use Ekman and sentiment mapping to create new columns with respective names. You need to write keywords for those mappings, not numbers. If there are multiple words, create a list.

**Note**: Again, hardcoding is not allowed, import those mapping files in your colab.

**Comment by Parvish-Kakarapalli** [comment]
claim

**Comment by KBVijayVarma** [comment]
Claim

**Comment by sunny7712** [comment]
claim
